/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackagesIdRouteImport } from './routes/packages.$id'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as TrainsRouteImport } from './routes/trains'
import { Route as HolidaysRouteImport } from './routes/holidays'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'

const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainsRoute = TrainsRouteImport.update({
  id: '/trains',
  path: '/trains',
  getParentRoute: () => rootRouteImport,
} as any)
const HolidaysRoute = HolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/admin/coupons',
  path: '/admin/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIdRoute = PackagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PackagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/flights': typeof FlightsRoute
  '/hotels': typeof HotelsRoute
  '/trains': typeof TrainsRoute
  '/holidays': typeof HolidaysRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/account': typeof AccountRoute
  '/bookings': typeof BookingsRoute
  '/compare': typeof CompareRoute
  '/saved': typeof SavedRoute
  '/packages': typeof PackagesRouteWithChildren
  '/packages/$id': typeof PackagesIdRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/flights': typeof FlightsRoute
  '/hotels': typeof HotelsRoute
  '/trains': typeof TrainsRoute
  '/holidays': typeof HolidaysRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/account': typeof AccountRoute
  '/bookings': typeof BookingsRoute
  '/compare': typeof CompareRoute
  '/saved': typeof SavedRoute
  '/packages': typeof PackagesRouteWithChildren
  '/packages/$id': typeof PackagesIdRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/flights': typeof FlightsRoute
  '/hotels': typeof HotelsRoute
  '/trains': typeof TrainsRoute
  '/holidays': typeof HolidaysRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/account': typeof AccountRoute
  '/bookings': typeof BookingsRoute
  '/compare': typeof CompareRoute
  '/saved': typeof SavedRoute
  '/packages': typeof PackagesRouteWithChildren
  '/packages/$id': typeof PackagesIdRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/flights' | '/hotels' | '/trains' | '/holidays' | '/login' | '/signup' | '/account' | '/bookings' | '/compare' | '/saved' | '/packages' | '/packages/$id' | '/admin/coupons' | '/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/flights' | '/hotels' | '/trains' | '/holidays' | '/login' | '/signup' | '/account' | '/bookings' | '/compare' | '/saved' | '/packages' | '/packages/$id' | '/admin/coupons' | '/auth/google/callback'
  id: '__root__' | '/' | '/about' | '/flights' | '/hotels' | '/trains' | '/holidays' | '/login' | '/signup' | '/account' | '/bookings' | '/compare' | '/saved' | '/packages' | '/packages/$id' | '/admin/coupons' | '/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FlightsRoute: typeof FlightsRoute
  HotelsRoute: typeof HotelsRoute
  TrainsRoute: typeof TrainsRoute
  HolidaysRoute: typeof HolidaysRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AccountRoute: typeof AccountRoute
  BookingsRoute: typeof BookingsRoute
  SavedRoute: typeof SavedRoute
  PackagesRoute: typeof PackagesRouteWithChildren
  AdminCouponsRoute: typeof AdminCouponsRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trains': {
      id: '/trains'
      path: '/trains'
      fullPath: '/trains'
      preLoaderRoute: typeof TrainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holidays': {
      id: '/holidays'
      path: '/holidays'
      fullPath: '/holidays'
      preLoaderRoute: typeof HolidaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$id': {
      id: '/packages/$id'
      path: '/$id'
      fullPath: '/packages/$id'
      preLoaderRoute: typeof PackagesIdRouteImport
      parentRoute: typeof PackagesRoute
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/admin/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PackagesRouteChildren {
  PackagesIdRoute: typeof PackagesIdRoute
}

const PackagesRouteChildren: PackagesRouteChildren = {
  PackagesIdRoute: PackagesIdRoute,
}

const PackagesRouteWithChildren = PackagesRoute._addFileChildren(
  PackagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FlightsRoute: FlightsRoute,
  HotelsRoute: HotelsRoute,
  TrainsRoute: TrainsRoute,
  HolidaysRoute: HolidaysRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AccountRoute: AccountRoute,
  BookingsRoute: BookingsRoute,
  CompareRoute: CompareRoute,
  SavedRoute: SavedRoute,
  PackagesRoute: PackagesRouteWithChildren,
  AdminCouponsRoute: AdminCouponsRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
